forex_options_list = [ 
    'AUDCAD', 
    'AUDCHF', 
    'AUDJPY', 
    'AUDNZD', 
    'AUDSGD', 
    'AUDUSD', 
    'CADCHF', 
    'CADHKD', 
    'CADJPY', 
    'CHFJPY', 
    'CHFSGD', 
    'EURAUD', 
    'EURCAD', 
    'EURCHF', 
    'EURCZK', 
    'EURDKK', 
    'EURGBP', 
    'EURHKD', 
    'EURHUF', 
    'EURJPY', 
    'EURNOK', 
    'EURNZD', 
    'EURPLN', 
    'EURRUB', 
    'EURSEK', 
    'EURSGD', 
    'EURTRY', 
    'EURUSD', 
    'GBPAUD', 
    'GBPCAD', 
    'GBPCHF', 
    'GBPJPY', 
    'GBPNZD', 
    'GBPUSD', 
    'HKDJPY', 
    'NZDCAD', 
    'NZDCHF', 
    'NZDJPY', 
    'NZDUSD', 
    'SGDJPY', 
    'TRYJPY', 
    'USDCAD', 
    'USDCHF', 
    'USDCNH', 
    'USDCZK', 
    'USDDKK', 
    'USDHKD', 
    'USDHUF', 
    'USDILS', 
    'USDJPY', 
    'USDMXN', 
    'USDNOK', 
    'USDPLN', 
    'USDRON', 
    'USDRUB', 
    'USDSEK', 
    'USDSGD', 
    'USDTHB', 
    'USDTRY', 
    'USDZAR', 
    'ZARJPY' 
]

commodity_options_list = {
    'Gas Oil (DIESEL.CMD/USD)' : 'DIESELCMDUSD', 
    'Natural Gas (GAS.CMD/USD)' : 'GASCMDUSD',
    'US Brent Crude Oil (BRENT.CMD/USD)' : 'BRENTCMDUSD',
    'US Light Crude Oil (LIGHT.CMD/USD)' : 'LIGHTCMDUSD',
    'Cocoa - NY (COCOA.CMD/USD)' : 'COCOCMDUSD', 
    'Coffee - Arabica (COFFEE.CMD/USX)' : 'COFFEECMDUSD', 
    'Cotton (COTTON.CMD/USX)' : 'COTTONCMDUSD', 
    'Orange Juice (OJUICE.CMD/USX)' : 'OJUICECMDUSD',
    'Soybeans (SOYBEAN.CMD/USX)' : 'SOYBEANCMDUSX', 
    'Sugar - London No. 5 (SUGAR.CMD/USD)' : 'SUGARCMDUSD'
}

crypto_options_list = {
    'Aave / USD' : 'AVEUSD',
    'Basic Attention Token / USD' : 'BATUSD',
    'Bitcoin Cash / USD' : 'BCHUSD',
    'Bitcoin / USD' : 'BTCUSD', 
    'Cardano / USD' : 'ADAUSD', 
    'Chainlink / USD' : 'LNKUSD',
    'Compound / USD' : 'CMPUSD', 
    'Dash / USD' : 'DSHUSD', 
    'Enjin / USD' : 'ENJUSD',
    'EOS / USD' : 'EOSUSD', 
    'Ethereum' : 'ETHUSD',
    'Litecoin / USD' : 'LTCUSD',
    'Maker / USD' : 'MKRUSD',
    'Monero / USD' : 'XMRUSD',
    'Polygon / USD' : 'MATUSD',
    'Stellar / USD' : 'XLMUSD',
    'Tron / USD' : 'TRXUSD',
    'Uniswap / USD' : 'UNIUSD',
    'Yearn Finance / USD' : 'YFIUSD'
}

index_options_list = {
    'US Dollar Index (DOLLAR.IDX/USD)' : 'DOLLARIDXUSD',
    'US 30 Index (USA30.IDX/USD' : 'USA30IDXUSD',
    'US 100 Tech Index (USATECH.IDX/USD' : 'USATECHIDXUSD', 
    'US 500 Index (USA500.IDX/USD' : 'USA500IDXUSD', 
    'US Small Cap 2000 (USSC2000.IDX/USD' : 'USSC2000IDXUSD', 
    'China A50 Index (CHI.IDX/USD)' : 'CHIIDXUSD', 
    'Hong Kong 40 Index (HKG.IDX/HKD)' : 'HKGIDXHKD', 
    'Japan 225 (JPN.IDX/JPY)' : 'JPNIDXJPY', 
    'Australia 200 (AUS.IDX/AUD)' : 'AUSIDXAUD', 
    'India 50 Index (IND.IDX/USD)' : 'INDIDXUSD', 
    'Singapore Bluechip Cash Index (SGD.IDX/SGD)' : 'SGDIDXSGD', 
    'France 40 Index (FRA.IDX/EUR)' : 'FRAIDXEUR', 
    'Germany 40 Index (DEU.IDX/EUR)' : 'DEUIDXEUR', 
    'Europe 50 Index (EUS.IDX/EUR)' : 'EUSIDXEUR', 
    'UK 100 Index (GBR.IDX/GBP)' : 'GBRIDXGBP', 
    'Spain 35 Index (ESP.IDX/EUR)' : 'ESPIDXEUR', 
    'Switzerland 20 Index (CHE.IDX/CHF)' : 'CHEIDXCHF', 
    'Netherlands 25 Index (NLD.IDX/EUR)' : 'NLDIDXEUR', 
    'Poland 20 Index (PLN.IDX/PLN)' : 'PLNIDXPLN', 
}

metal_options_list = {
    'Copper - High Grade (COPPER.CMD/USD)' : 'COPPERCMDUSD', 
    'Spot Gold (XAU/USD)' : 'XAUUSD',
    'Spot Silver (XAG/USD)' : 'XAGUSD',
}

bond_options_list = {
    'Euro Bund (BUND.TR/EUR)' : 'BUNDTREUR', 
    'UK Long Gilt (UKGILT.TR/GBP)' : 'UKGILTTRGBP',
    'US T-Bond (USTBOND.TR/USD)' : 'USTBONDTRUSD',
}