forex_options_list = [ 
    'AUDCAD', 
    'AUDCHF', 
    'AUDJPY', 
    'AUDNZD', 
    'AUDSGD', 
    'AUDUSD', 
    'CADCHF', 
    'CADHKD', 
    'CADJPY', 
    'CHFJPY', 
    'CHFSGD', 
    'EURAUD', 
    'EURCAD', 
    'EURCHF', 
    'EURCZK', 
    'EURDKK', 
    'EURGBP', 
    'EURHKD', 
    'EURHUF', 
    'EURJPY', 
    'EURNOK', 
    'EURNZD', 
    'EURPLN', 
    'EURRUB', 
    'EURSEK', 
    'EURSGD', 
    'EURTRY', 
    'EURUSD', 
    'GBPAUD', 
    'GBPCAD', 
    'GBPCHF', 
    'GBPJPY', 
    'GBPNZD', 
    'GBPUSD', 
    'HKDJPY', 
    'NZDCAD', 
    'NZDCHF', 
    'NZDJPY', 
    'NZDUSD', 
    'SGDJPY', 
    'TRYJPY', 
    'USDCAD', 
    'USDCHF', 
    'USDCNH', 
    'USDCZK', 
    'USDDKK', 
    'USDHKD', 
    'USDHUF', 
    'USDILS', 
    'USDJPY', 
    'USDMXN', 
    'USDNOK', 
    'USDPLN', 
    'USDRON', 
    'USDRUB', 
    'USDSEK', 
    'USDSGD', 
    'USDTHB', 
    'USDTRY', 
    'USDZAR', 
    'ZARJPY' 
]

commodity_options_list = {
    'Diesel (Gas Oil)' : 'DIESELCMDUSD', 
    'Natural Gas' : 'GASCMDUSD',
    'US Brent Crude' : 'BRENTCMDUSD',
    'US Light Crude' : 'LIGHTCMDUSD',
    'Cocoa (NY)' : 'COCOCMDUSD', 
    'Coffee (Arabica)' : 'COFFEECMDUSD', 
    'Cotton' : 'COTTONCMDUSD', 
    'Orange Juice' : 'OJUICECMDUSD',
    'Soybeans' : 'SOYBEANCMDUSX', 
    'Sugar (London No. 5)' : 'SUGARCMDUSD'
}

crypto_options_list = {
    'Aave / USD' : 'AVEUSD',
    'Basic Attention Token / USD' : 'BATUSD',
    'Bitcoin Cash / USD' : 'BCHUSD',
    'Bitcoin / USD' : 'BTCUSD', 
    'Cardano / USD' : 'ADAUSD', 
    'Chainlink / USD' : 'LNKUSD',
    'Compound / USD' : 'CMPUSD', 
    'Dash / USD' : 'DSHUSD', 
    'Enjin / USD' : 'ENJUSD',
    'EOS / USD' : 'EOSUSD', 
    'Ethereum' : 'ETHUSD',
    'Litecoin / USD' : 'LTCUSD',
    'Maker / USD' : 'MKRUSD',
    'Monero / USD' : 'XMRUSD',
    'Polygon / USD' : 'MATUSD',
    'Stellar / USD' : 'XLMUSD',
    'Tron / USD' : 'TRXUSD',
    'Uniswap / USD' : 'UNIUSD',
    'Yearn Finance / USD' : 'YFIUSD'
}

index_options_list = {
    'US Dollar Index' : 'DOLLARIDXUSD',
    'US 30 Index' : 'USA30IDXUSD',
    'US 100 Tech Index' : 'USATECHIDXUSD', 
    'US 500 Index' : 'USA500IDXUSD', 
    'US Small Cap 2000' : 'USSC2000IDXUSD', 
}